name: "[basic-report] Test"

on:
  push:
    paths:
      - 'basic-report/**'
      - .github/workflows/basic-report-test.yml
  pull_request:
    paths:
      - 'basic-report/**'
      - .github/workflows/basic-report-test.yml
  workflow_dispatch:

defaults:
  run:
    working-directory: ./basic-report

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 7

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 13

      - name: Install npm packages
        run: npm install

      - name: Compile scripts
        run: npm run compile
