name: "[section-report] Test"

on:
  push:
    paths:
      - 'section-report/**'
      - .github/workflows/section-report-test.yml
  pull_request:
    paths:
      - 'section-report/**'
      - .github/workflows/section-report-test.yml
  workflow_dispatch:

defaults:
  run:
    working-directory: section-report

jobs:
  build:
    runs-on: ubuntu-latest
    # Run this build only on either pull request or push.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        node-version:
          - 13.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build and test with lint
      run: |
        npm install
        npm run test:lint
        npm run build
        npm run test:unit
