name: "[section-editor] Build and release"

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

defaults:
  run:
    working-directory: section-editor

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            package-ext: .dmg
          - os: ubuntu-latest
            package-ext: .AppImage
          - os: windows-latest
            package-ext: .exe

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: Install npm packages
        run: npm install

      - name: Build package
        run: npm run electron:build

      - name: Prepare package
        run: |
          mkdir package
          mv dist_electron/*${{ matrix.package-ext }} package/

      - name: Upload to artifact if not tagged
        uses: actions/upload-artifact@v2
        if: "!startsWith(github.ref, 'refs/tags')"
        with:
          name: ${{ matrix.os }}
          path: section-editor/package/*${{ matrix.package-ext }}

      - name: Release if tagged
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "section-editor/package/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
